package com.project.demo;

import com.project.demo.model.*;
import com.project.demo.repository.*;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;

import static org.junit.jupiter.api.Assertions.*;

@DataJpaTest
public class RepositoryMappingTest {

    @Autowired
    private CandidatRepository candidatRepository;

    @Autowired
    private AngajatorRepository angajatorRepository;

    @Autowired
    private AnuntRepository anuntRepository;

    @Autowired
    private AplicareRepository aplicareRepository;

    // You need this to save the company before attaching it to the employer
    @Autowired
    private CompanieRepository companieRepository;

    @Test
    public void testJoinedInheritanceAndApplicationLogic() {
        // 1. Test Inheritance: Create a Candidat and check if User fields work
        Candidat candidat = new Candidat();
        candidat.setNumeUser("Andrei Ionescu");
        candidat.setEmail("andrei@example.com");
        candidat.setParola("securepass");

        Candidat savedCandidat = candidatRepository.save(candidat);
        assertNotNull(savedCandidat.getIdUser(), "Candidat ID should be generated by DB");
        assertEquals("CANDIDAT", savedCandidat.getRol(), "Polymorphic role must be CANDIDAT");

        // 2. Create and save the Companie first
        Companie companie = new Companie();
        companie.setNumeCompanie("Tech Solutions");
        companie.setDomeniu("IT");
        companie.setLocatie("Bucuresti");
        Companie savedCompanie = companieRepository.save(companie);

        // 3. Test Angajator and Anunt Mapping
        Angajator angajator = new Angajator();
        angajator.setNumeUser("Companie IT SRL");
        angajator.setEmail("hr@company.com");
        angajator.setParola("companypass");
        angajator.setCompanie(savedCompanie); // Pass the actual object, not a String
        Angajator savedAngajator = angajatorRepository.save(angajator);

        Anunt anunt = new Anunt();
        anunt.setTitlu("Java Developer Backend");
        anunt.setDescriereJob("Looking for someone who writes clean code...");
        anunt.setSalariuMin(5000.0);
        anunt.setSalariuMax(8000.0);
        anunt.setAngajator(savedAngajator);
        Anunt savedAnunt = anuntRepository.save(anunt);

        assertNotNull(savedAnunt.getId(), "Anunt ID should be generated");
        assertEquals(savedAngajator.getIdUser(), savedAnunt.getAngajator().getIdUser());

        // 4. Test the core relational entity: Aplicare (The bridge table)
        Aplicare aplicare = new Aplicare();
        aplicare.setCandidat(savedCandidat);
        aplicare.setAnunt(savedAnunt);
        aplicare.setProbabilitateCompatibilitate(85.5);

        Aplicare savedAplicare = aplicareRepository.save(aplicare);

        // 5. Assertions: Prove your database constraints actually work
        assertNotNull(savedAplicare.getIdAplicare());
        assertEquals("Andrei Ionescu", savedAplicare.getCandidat().getNumeUser(), "Inherited User field failed to fetch through Aplicare relationship");
        assertEquals("Java Developer Backend", savedAplicare.getAnunt().getTitlu(), "Anunt relationship mapping is broken");
        assertEquals(85.5, savedAplicare.getProbabilitateCompatibilitate());
    }
}