spring.application.name=demo
spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:postgresql://localhost:5433/jobportal
spring.datasource.username=postgres
spring.datasource.password=parola
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.max-file-size=16MB
spring.servlet.multipart.max-request-size=16MB
spring.profiles.active=local
ocr.tessdata.path=./tessdata
ocr.language=ron+eng

# Configurari Agent Angajator (Groq / Llama)
#spring.ai.openai.api-key=${OPENAI_API_KEY}
OPENAI_API_KEY=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
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.openai.chat.options.temperature=0.7

#Configurari Agent Candidat
gemini.api.key=AQ.Ab8RN6I8Jx71W_FYd4R1lPwr1ZHgf86YINYDCK--Uw-INoDtIQ


