spring.application.name=demo
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:postgresql://localhost:5433/jobportal
spring.datasource.username=postgres
spring.datasource.password=parola
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
gemini.api.key=${GEMINI_API_KEY}
server.port=8081