
spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.openai.chat.options.temperature=0.7